### ISSUE TITLE
HexChat Notice Colors

### ISSUE THREAD

**Issue by LunarEclipse120** [shaunduncan/xchat-colorize#5] opened 2016-12-17 21:44 UTC
With the new update to HexChat, there is an issue caused by Colorize where HexChat won't update the new data notice on the channel swithcer to the new message color if a message arrives. I've asked around and I think I found the solution is to add "xchat.command('gui color 2')" to line 134 with 1 indent, however I don't know if this will make the addon not work with other versions. Thanks you.

**Comment by shaunduncan** [comment] 2017-01-05 21:40
Sorry for the delay in responding to this. Would you mind submitting a pull request with your suggestion? That sounds like a reasonable change to me. I'm also not sure how that would behave with older versions, but maybe a try/except around the command could work?

**Comment by noahajac** [comment] 2017-01-17 21:22
Pull request has been merged so the issue is fixed. Thanks!

**Closed by noahajac** 2017-01-17 21:22 UTC
